### PR TITLE
RiskReward 

### PR DESCRIPTION
**Pull request by alibanihashemi**

### CODE REVIEW

**Comment by wbarfuss** [comment]
Thanks, Ali. Which version of nbdev are you using?

**Comment by alibanihashemi** [comment]
> Thanks, Ali. Which version of nbdev are you using?
Hi wolf here is the info:
Name: nbdev
Version: 2.3.29
Summary: Create delightful software with Jupyter Notebooks
Home-page: https://github.com/fastai/nbdev
Author: Jeremy Howard and Hamel Husain
Author-email: j@fast.ai
License: Apache Software License 2.0
Location: /home/localuser/anaconda3/envs/pyCRLD_dev/lib/python3.8/site-packages
Requires: asttokens, astunparse, execnb, fastcore, ghapi, packaging, PyYAML, watchdog
Required-by:

**Comment by wbarfuss** [comment]
Thanks. I upgraded to the latest nbdev version. This would resolve many files that changed on your PR without you touching them. Can you please try to integrate my change into your PR?

**Comment by alibanihashemi** [comment]
> Thanks. I upgraded to the latest nbdev version. This would resolve many files that changed on your PR without you touching them. Can you please try to integrate my change into your PR?

Good morning Wolf,
I integrated your changes into a new PR.

**Pull request closed without merging**
