### PR TITLE
Risk rewrad

### PR DESCRIPTION
**Pull request by alibanihashemi**

### CODE REVIEW

**Comment by wbarfuss** [comment]
Hi Ali, how are you doing on this PR?

**Comment by alibanihashemi** [comment]
Hi wolf,
The main branch has passed CI test. I deleted RiskReward branch. Pls let me know if I got you right!

**Comment by alibanihashemi** [comment]
> Hi Ali, how are you doing on this PR?

Hi wolf,
The main branch has passed CI test. I deleted RiskReward branch. Pls let me know if I got you right!

**Comment by wbarfuss** [comment]
Deleting your RiskReward branch has closed this pull request. We still need to integrate the risk-reward environment into the main package. Maybe you have to open another pull request / branch for that?

**Pull request closed without merging**
